# ---------------------CLASS 3----------------------------


## NUMPY Operation

In [1]:
import numpy as np


In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#addition
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# sub
arr -arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
arr + 33

array([33, 34, 35, 36, 37, 38, 39, 40, 41, 42])

In [13]:
arr - 500

array([-500, -499, -498, -497, -496, -495, -494, -493, -492, -491])

In [14]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

### nan  VS  inf in the O/P

In [16]:
arr/arr

C:\Users\RAHUL\AppData\Local\Temp\ipykernel_2020\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [17]:
1/arr

C:\Users\RAHUL\AppData\Local\Temp\ipykernel_2020\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

## universal array function

In [18]:
# taking sqroot of every elent in the array

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [19]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [20]:
np.max(arr)

9

In [21]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [22]:
# https://docs.scipy.org/doc/numpy-1.9.3/reference/ufuncs.html#math-operations